/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "isr_LED_ring.h"
#include "Timer3.h"
#include "isr_LED_pulse.h"
#include "Timer2.h"
#include "timer_clock_1.h"
#include "isr_LED_refreshrate.h"
#include "Timer1.h"
#include "LEDdata2_aliases.h"
#include "LEDdata2.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "LEDdata_aliases.h"
#include "LEDdata.h"
#include "ADC_DelSig_1.h"
#include "PlayerSelect.h"
#include "UART_1.h"
#include "isr_uart_rx.h"
#include "SAR_p2_aliases.h"
#include "SAR_p2.h"
#include "isr_button.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "SAR_p1_aliases.h"
#include "SAR_p1.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "SPIMOutCtrl.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "SDA_pin_aliases.h"
#include "SDA_pin.h"
#include "SCL_pin_aliases.h"
#include "SCL_pin.h"
#include "Timer_Stopur.h"
#include "isr_timer.h"
#include "Timer_LCD.h"
#include "isr_refreshrate_LCD.h"
#include "Timer4.h"
#include "isr_BlinkLED.h"
#include "isr_delay.h"
#include "Timer5.h"
#include "SPI_int_aliases.h"
#include "SPI_int.h"
#include "SPIS.h"
#include "SPIS_PVT.h"
#include "SS_aliases.h"
#include "SS.h"
#include "rx_isr.h"
#include "SPIM_1_IntClock.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "UART_1_IntClock.h"
#include "SPIS_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

