/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LEDdata_aliases.h"
#include "LEDdata.h"
#include "LEDdata2_aliases.h"
#include "LEDdata2.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "timer_clock.h"
#include "Timer1.h"
#include "isr_LED_refreshrate.h"
#include "timer_clock_1.h"
#include "Timer2.h"
#include "isr_LED_pulse.h"
#include "timer_clock_2.h"
#include "Timer3.h"
#include "isr_LED_ring.h"
#include "SPIMOutCtrl.h"
#include "timer_clock_3.h"
#include "Timer4.h"
#include "isr_BlinkLED.h"
#include "isr_delay.h"
#include "timer_clock_4.h"
#include "Timer5.h"
#include "SPIM_1_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

